kind: pipeline
type: exec
name: win_build

platform:
  os: windows
  arch: amd64

clone:
  depth: 1

trigger:
  branch:
  - server-gui-win

steps:
- name: build_tts_server
  commands:
  - git submodule update --init --recursive --depth=1
  - cd third-party\coqui-ai-tts
  - .\install\pip_build_win.bat
  - .\install\pyinstaller_win.bat
  - cp install\dist\tts_server_wrapper.exe ..\..\install\tts-server.exe

- name: build
  commands:
  - git submodule update --init --recursive --depth=1
  - python -m venv venv
  - .\venv\Scripts\activate
  - pip install wheel
  - pip install ./third-party/coqui-ai-tts
  - pip install -r requirements.txt
  - pip install -e .
  - pip uninstall pyqtconfig -y
  - pip install git+https://github.com/pythonguis/pyqtconfig.git
  - pip install torch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0
  
- name: run_pyinstaller
  commands:
  - .\venv\Scripts\activate
  - pip install pyinstaller
  - cd install
  - .\build_win.bat

- name: copy_hack
  commands:
  - 'cp install\dist\app.exe C:\Drone\coqui-tts-server-gui.exe'
